// <auto-generated />
using System;
using IsTakip.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IsTakip.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230329195611_1001-firstMigration")]
    partial class _1001firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IsTakip.Entities.Classes.AjandaClasses.Ajanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NotTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Ajandas");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.AlinanIslerClasses.AlinanIsler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("Fiyat")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBitimindeBildir")
                        .HasColumnType("bit");

                    b.Property<string>("IsNotu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Iscilik")
                        .HasColumnType("bit");

                    b.Property<int>("KalinlikId")
                        .HasColumnType("int");

                    b.Property<string>("MalzemeNotu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MalzemeTipId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriSiparisNo")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("TeklifNo")
                        .HasColumnType("int");

                    b.Property<bool>("Teklifli")
                        .HasColumnType("bit");

                    b.Property<string>("Termin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KalinlikId");

                    b.HasIndex("MalzemeTipId");

                    b.HasIndex("MusteriId");

                    b.ToTable("AlinanIslers");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.DepoClasses.Depo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yetkili")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YetkiliTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Depos");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.DepoEnvanterClasses.DepoEnvanter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<float>("Agirlik")
                        .HasColumnType("real");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<float>("Boy")
                        .HasColumnType("real");

                    b.Property<int>("DepoId")
                        .HasColumnType("int");

                    b.Property<int>("DepoRafId")
                        .HasColumnType("int");

                    b.Property<float>("En")
                        .HasColumnType("real");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("KalinlikId")
                        .HasColumnType("int");

                    b.Property<int>("MalzemeTipId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DepoId");

                    b.HasIndex("DepoRafId")
                        .IsUnique();

                    b.HasIndex("KalinlikId");

                    b.HasIndex("MalzemeTipId");

                    b.HasIndex("MusteriId");

                    b.ToTable("DepoEnvanters");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.DepoRafClasses.DepoRaf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Deporafs");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.DurusTipClasses.DurusTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DurusTips");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.IsDosyaClasses.IsDosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("AlinanIslerId")
                        .HasColumnType("int");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AlinanIslerId");

                    b.ToTable("IsDosyas");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.IsOnceligiClasses.IsOnceligi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("AlinanIslerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AlinanIslerId");

                    b.ToTable("IsOnceligis");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.KalinlikClasses.Kalinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("MalzemeTipId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MalzemeTipId");

                    b.ToTable("kalinliks");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.KullaniciClasses.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciKodu")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MailBildirimi")
                        .HasColumnType("bit");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("RolTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Kullanicis");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.MailParametreleriClasses.MailParametreleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SSLKullan")
                        .HasColumnType("bit");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("SmtpAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpPort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MailParametreleris");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.MalzemeClasses.MalzemeTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("malzemeTips");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.MusteriClasses.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriSinifId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VergiDairesiNumarasi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MusteriSinifId");

                    b.ToTable("musteris");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.MusteriKisitlamaClasses.MusteriKisitlama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("IslemAciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Kisitlama")
                        .HasColumnType("bit");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("MusteriKisitlamas");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.MusteriSinifClasses.MusteriSinif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("MusteriSınıfs");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.MusteriTemsilciClasses.MusteriTemsilci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("MusteriTemsilcis");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.TedarikciClasses.Tedarikci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("int");

                    b.Property<int>("MalzemeTipsId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MalzemeTipsId");

                    b.ToTable("Tedarikcis");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.UretimDrumClasses.UretimDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UretimDurums");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.UretimDurusClasses.UretimDurus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DurusSuresi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurusTipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("UretimEmriId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DurusTipId");

                    b.HasIndex("UretimEmriId");

                    b.ToTable("UretimDurus");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.UretimEmriClasses.UretimEmri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AilnanIslerId")
                        .HasColumnType("int");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("AlinanIslerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsEmriTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ToplamDurusSuresi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UretimBaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UretimDrumId")
                        .HasColumnType("int");

                    b.Property<int>("UretimDurumsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UretimTamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlinanIslerId");

                    b.HasIndex("UretimDurumsId");

                    b.ToTable("UretimEmris");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.AjandaClasses.Ajanda", b =>
                {
                    b.HasOne("IsTakip.Entities.Classes.MusteriClasses.Musteri", "Musteri")
                        .WithMany("Ajanda")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.AlinanIslerClasses.AlinanIsler", b =>
                {
                    b.HasOne("IsTakip.Entities.Classes.KalinlikClasses.Kalinlik", "Kalinliks")
                        .WithMany("AlinanIslers")
                        .HasForeignKey("KalinlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsTakip.Entities.Classes.MalzemeClasses.MalzemeTip", "MalzemeTips")
                        .WithMany("AlinanIsler")
                        .HasForeignKey("MalzemeTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsTakip.Entities.Classes.MusteriClasses.Musteri", "musteris")
                        .WithMany("AlinanIsler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kalinliks");

                    b.Navigation("MalzemeTips");

                    b.Navigation("musteris");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.DepoEnvanterClasses.DepoEnvanter", b =>
                {
                    b.HasOne("IsTakip.Entities.Classes.DepoClasses.Depo", "Depo")
                        .WithMany("DepoEnvanter")
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsTakip.Entities.Classes.DepoRafClasses.DepoRaf", "DepoRaf")
                        .WithOne("DepoEnvanter")
                        .HasForeignKey("IsTakip.Entities.Classes.DepoEnvanterClasses.DepoEnvanter", "DepoRafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsTakip.Entities.Classes.KalinlikClasses.Kalinlik", "Kalinlik")
                        .WithMany("DepoEnvanters")
                        .HasForeignKey("KalinlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsTakip.Entities.Classes.MalzemeClasses.MalzemeTip", "malzemeTip")
                        .WithMany("DepoEnvanter")
                        .HasForeignKey("MalzemeTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsTakip.Entities.Classes.MusteriClasses.Musteri", "musteri")
                        .WithMany("DepoEnvanter")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depo");

                    b.Navigation("DepoRaf");

                    b.Navigation("Kalinlik");

                    b.Navigation("malzemeTip");

                    b.Navigation("musteri");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.IsDosyaClasses.IsDosya", b =>
                {
                    b.HasOne("IsTakip.Entities.Classes.AlinanIslerClasses.AlinanIsler", "AlinanIslers")
                        .WithMany("ısDosyas")
                        .HasForeignKey("AlinanIslerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlinanIslers");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.IsOnceligiClasses.IsOnceligi", b =>
                {
                    b.HasOne("IsTakip.Entities.Classes.AlinanIslerClasses.AlinanIsler", "AlinanIsler")
                        .WithMany("IsOnceligis")
                        .HasForeignKey("AlinanIslerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlinanIsler");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.KalinlikClasses.Kalinlik", b =>
                {
                    b.HasOne("IsTakip.Entities.Classes.MalzemeClasses.MalzemeTip", null)
                        .WithMany("kalinliks")
                        .HasForeignKey("MalzemeTipId");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.KullaniciClasses.Kullanici", b =>
                {
                    b.HasOne("IsTakip.Entities.Classes.MusteriClasses.Musteri", "Musteri")
                        .WithMany("Kullanici")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.MusteriClasses.Musteri", b =>
                {
                    b.HasOne("IsTakip.Entities.Classes.MusteriSinifClasses.MusteriSinif", "MusteriSinif")
                        .WithMany("Musteriler")
                        .HasForeignKey("MusteriSinifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusteriSinif");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.MusteriKisitlamaClasses.MusteriKisitlama", b =>
                {
                    b.HasOne("IsTakip.Entities.Classes.MusteriClasses.Musteri", "Musteri")
                        .WithMany("kisitlama")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.MusteriTemsilciClasses.MusteriTemsilci", b =>
                {
                    b.HasOne("IsTakip.Entities.Classes.MusteriClasses.Musteri", "Musteri")
                        .WithMany("MusteriTemsilci")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.TedarikciClasses.Tedarikci", b =>
                {
                    b.HasOne("IsTakip.Entities.Classes.MalzemeClasses.MalzemeTip", "MalzemeTips")
                        .WithMany("Tedarikcis")
                        .HasForeignKey("MalzemeTipsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MalzemeTips");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.UretimDurusClasses.UretimDurus", b =>
                {
                    b.HasOne("IsTakip.Entities.Classes.DurusTipClasses.DurusTip", "DurusTips")
                        .WithMany("UretimDurus")
                        .HasForeignKey("DurusTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsTakip.Entities.Classes.UretimEmriClasses.UretimEmri", "UretimEmri")
                        .WithMany()
                        .HasForeignKey("UretimEmriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DurusTips");

                    b.Navigation("UretimEmri");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.UretimEmriClasses.UretimEmri", b =>
                {
                    b.HasOne("IsTakip.Entities.Classes.AlinanIslerClasses.AlinanIsler", "AlinanIsler")
                        .WithMany("UretimEmris")
                        .HasForeignKey("AlinanIslerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsTakip.Entities.Classes.UretimDrumClasses.UretimDurum", "UretimDurums")
                        .WithMany("UretimEmris")
                        .HasForeignKey("UretimDurumsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlinanIsler");

                    b.Navigation("UretimDurums");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.AlinanIslerClasses.AlinanIsler", b =>
                {
                    b.Navigation("IsOnceligis");

                    b.Navigation("UretimEmris");

                    b.Navigation("ısDosyas");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.DepoClasses.Depo", b =>
                {
                    b.Navigation("DepoEnvanter");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.DepoRafClasses.DepoRaf", b =>
                {
                    b.Navigation("DepoEnvanter")
                        .IsRequired();
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.DurusTipClasses.DurusTip", b =>
                {
                    b.Navigation("UretimDurus");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.KalinlikClasses.Kalinlik", b =>
                {
                    b.Navigation("AlinanIslers");

                    b.Navigation("DepoEnvanters");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.MalzemeClasses.MalzemeTip", b =>
                {
                    b.Navigation("AlinanIsler");

                    b.Navigation("DepoEnvanter");

                    b.Navigation("Tedarikcis");

                    b.Navigation("kalinliks");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.MusteriClasses.Musteri", b =>
                {
                    b.Navigation("Ajanda");

                    b.Navigation("AlinanIsler");

                    b.Navigation("DepoEnvanter");

                    b.Navigation("Kullanici");

                    b.Navigation("MusteriTemsilci");

                    b.Navigation("kisitlama");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.MusteriSinifClasses.MusteriSinif", b =>
                {
                    b.Navigation("Musteriler");
                });

            modelBuilder.Entity("IsTakip.Entities.Classes.UretimDrumClasses.UretimDurum", b =>
                {
                    b.Navigation("UretimEmris");
                });
#pragma warning restore 612, 618
        }
    }
}
